add_subdirectory(testingUtilities)
add_subdirectory(utilities)
add_subdirectory(command)
add_subdirectory(sdk)
add_subdirectory(io)
add_subdirectory(dataModel/nodes)
#add_subdirectory(dataModel/connection)
add_subdirectory(gui)
#add_subdirectory(plugin_manager)
add_subdirectory(test_plugins/test_plugin_a)
add_subdirectory(test_plugins/test_plugin_b)
